In [1]:
import pandas as pd
import numpy as np

In [2]:
path = r"C:\Users\micha\OneDrive\Documents\PRSGWAS_tsv\GCST90104550_buildGRCh37AA.tsv\Meta_IS_BothMandF_GIGA_AA_allfiles_metaAnalyseSEbased_wogc_2021June11_NeNs3rdDp1e6.gwascatalog.tsv_2"
gwas_AAdata = pd.read_csv(path, sep='\t')
display(gwas_AAdata)

,chromosome,base_pair_location,effect_allele_frequency,beta,standard_error,p_value,odds_ratio,ci_lower,ci_upper,effect_allele,other_allele
0,5,85928892,0.2814,-0.1045,0.0685,0.12700,0.900775,0.787604,1.030207,T,C
1,14,36082010,0.0636,0.1081,0.0896,0.22770,1.114159,0.934713,1.328056,T,C
2,10,128341232,0.6844,-0.0508,0.0633,0.42270,0.950469,0.839568,1.076019,T,C
3,18,51112281,0.8654,-0.0778,0.0601,0.19540,0.925149,0.822344,1.040807,T,C
4,4,55643311,0.1212,-0.1607,0.0936,0.08595,0.851547,0.708818,1.023017,T,C
...,...,...,...,...,...,...,...,...,...,...,...
8357157,4,113306346,0.2058,0.0405,0.0515,0.43160,1.041331,0.941350,1.151931,A,C
8357158,7,118234612,0.3731,-0.0282,0.0421,0.50260,0.972194,0.895193,1.055818,A,G
8357159,18,44156714,0.3583,-0.0704,0.0441,0.11020,0.932021,0.854844,1.016165,C,G
8357160,22,19966042,0.0947,-0.0464,0.0740,0.53060,0.954660,0.825769,1.103669,A,G
8357161,3,181867629,0.1957,0.0100,0.0631,0.87430,1.010050,0.892547,1.143022,T,C

In [3]:
rename_dict = {
    'chromosome': 'CHR',
    'base_pair_location': 'BP',
    'effect_allele': 'A1',      # A1 is the target/risk allele
    'other_allele': 'A2',       # A2 is the baseline allele
    'beta': 'BETA',
    'p_value': 'P',
    'effect_allele_frequency': 'EAF',
    'standard_error': 'SE',
    'odds_ratio': 'OR'
}

In [4]:
aarename = gwas_AAdata.rename(columns=rename_dict)

In [5]:
aarename

,CHR,BP,EAF,BETA,SE,P,OR,ci_lower,ci_upper,A1,A2
0,5,85928892,0.2814,-0.1045,0.0685,0.12700,0.900775,0.787604,1.030207,T,C
1,14,36082010,0.0636,0.1081,0.0896,0.22770,1.114159,0.934713,1.328056,T,C
2,10,128341232,0.6844,-0.0508,0.0633,0.42270,0.950469,0.839568,1.076019,T,C
3,18,51112281,0.8654,-0.0778,0.0601,0.19540,0.925149,0.822344,1.040807,T,C
4,4,55643311,0.1212,-0.1607,0.0936,0.08595,0.851547,0.708818,1.023017,T,C
...,...,...,...,...,...,...,...,...,...,...,...
8357157,4,113306346,0.2058,0.0405,0.0515,0.43160,1.041331,0.941350,1.151931,A,C
8357158,7,118234612,0.3731,-0.0282,0.0421,0.50260,0.972194,0.895193,1.055818,A,G
8357159,18,44156714,0.3583,-0.0704,0.0441,0.11020,0.932021,0.854844,1.016165,C,G
8357160,22,19966042,0.0947,-0.0464,0.0740,0.53060,0.954660,0.825769,1.103669,A,G
8357161,3,181867629,0.1957,0.0100,0.0631,0.87430,1.010050,0.892547,1.143022,T,C

In [7]:
columns_to_keep = ['CHR', 'BP', 'A1', 'A2', 'BETA', 'P', 'EAF', 'SE', 'OR'] 
aa = aarename[columns_to_keep]
aa

         CHR         BP A1 A2    BETA        P     EAF      SE        OR
0          5   85928892  T  C -0.1045  0.12700  0.2814  0.0685  0.900775
1         14   36082010  T  C  0.1081  0.22770  0.0636  0.0896  1.114159
2         10  128341232  T  C -0.0508  0.42270  0.6844  0.0633  0.950469
3         18   51112281  T  C -0.0778  0.19540  0.8654  0.0601  0.925149
4          4   55643311  T  C -0.1607  0.08595  0.1212  0.0936  0.851547
...      ...        ... .. ..     ...      ...     ...     ...       ...
8357157    4  113306346  A  C  0.0405  0.43160  0.2058  0.0515  1.041331
8357158    7  118234612  A  G -0.0282  0.50260  0.3731  0.0421  0.972194
8357159   18   44156714  C  G -0.0704  0.11020  0.3583  0.0441  0.932021
8357160   22   19966042  A  G -0.0464  0.53060  0.0947  0.0740  0.954660
8357161    3  181867629  T  C  0.0100  0.87430  0.1957  0.0631  1.010050

[8357162 rows x 9 columns]

In [8]:
missing = aa.isna().sum()
print(missing)

CHR     0
BP      0
A1      0
A2      0
BETA    0
P       0
EAF     0
SE      0
OR      0
dtype: int64

In [9]:
aa['MAF'] = np.where(
    aa['EAF'] > 0.5,     # The IF condition because Minor Alleles need to be less than 0.5, if effect allele is less than 0.5, calculation does not apply and MAF = EAF
    1 - aa['EAF'],       # What to do if TRUE
    aa['EAF']            # What to do if FALSE
)

C:\Users\micha\AppData\Local\Temp\ipykernel_6424\1180819115.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aa['MAF'] = np.where(

In [10]:
aa

,CHR,BP,A1,A2,BETA,P,EAF,SE,OR,MAF
0,5,85928892,T,C,-0.1045,0.12700,0.2814,0.0685,0.900775,0.2814
1,14,36082010,T,C,0.1081,0.22770,0.0636,0.0896,1.114159,0.0636
2,10,128341232,T,C,-0.0508,0.42270,0.6844,0.0633,0.950469,0.3156
3,18,51112281,T,C,-0.0778,0.19540,0.8654,0.0601,0.925149,0.1346
4,4,55643311,T,C,-0.1607,0.08595,0.1212,0.0936,0.851547,0.1212
...,...,...,...,...,...,...,...,...,...,...
8357157,4,113306346,A,C,0.0405,0.43160,0.2058,0.0515,1.041331,0.2058
8357158,7,118234612,A,G,-0.0282,0.50260,0.3731,0.0421,0.972194,0.3731
8357159,18,44156714,C,G,-0.0704,0.11020,0.3583,0.0441,0.932021,0.3583
8357160,22,19966042,A,G,-0.0464,0.53060,0.0947,0.0740,0.954660,0.0947
8357161,3,181867629,T,C,0.0100,0.87430,0.1957,0.0631,1.010050,0.1957

In [11]:
# Find the lowest and highest EAF in your data, for sanity check if calculations were wrong
min_eaf = aa['EAF'].min() 
max_eaf = aa['EAF'].max()

print(f"The lowest EAF is: {min_eaf}")
print(f"The highest EAF is: {max_eaf}")

The lowest EAF is: 0.0193
The highest EAF is: 0.9808

In [12]:
aa = aa[aa['MAF'] >= 0.01] # Filtering SNPs with MAF less than 1%, theory is this may be only noise

In [13]:
# Check for duplicate SNPs
print(aa.duplicated(subset=['CHR', 'BP']).sum())

0

In [14]:
min_p = aa['P'].min() 
max_p = aa['P'].max()

print(f"The lowest p is: {min_p}")
print(f"The highest p is: {max_p}")

The lowest p is: 3.352e-08
The highest p is: 1.0

In [15]:
aa = aa[(aa['P'] > 0) & (aa['P'] <= 1)]

In [16]:
aa

,CHR,BP,A1,A2,BETA,P,EAF,SE,OR,MAF
0,5,85928892,T,C,-0.1045,0.12700,0.2814,0.0685,0.900775,0.2814
1,14,36082010,T,C,0.1081,0.22770,0.0636,0.0896,1.114159,0.0636
2,10,128341232,T,C,-0.0508,0.42270,0.6844,0.0633,0.950469,0.3156
3,18,51112281,T,C,-0.0778,0.19540,0.8654,0.0601,0.925149,0.1346
4,4,55643311,T,C,-0.1607,0.08595,0.1212,0.0936,0.851547,0.1212
...,...,...,...,...,...,...,...,...,...,...
8357157,4,113306346,A,C,0.0405,0.43160,0.2058,0.0515,1.041331,0.2058
8357158,7,118234612,A,G,-0.0282,0.50260,0.3731,0.0421,0.972194,0.3731
8357159,18,44156714,C,G,-0.0704,0.11020,0.3583,0.0441,0.932021,0.3583
8357160,22,19966042,A,G,-0.0464,0.53060,0.0947,0.0740,0.954660,0.0947
8357161,3,181867629,T,C,0.0100,0.87430,0.1957,0.0631,1.010050,0.1957

In [17]:
aa.to_csv('AA_Data_Gigastroke_Cleaned.txt', sep='\t', index=False)