In [4]:
import pandas as pd
import numpy as np

In [5]:
path = r"C:\Users\micha\OneDrive\Documents\PRSGWAS_tsv\GCST90104540_buildGRCh37EU.tsv\Meta_IS_BothMandF_GIGA_EA_allfiles_metaAnalyseSEbased_wogc_2021June11_NeNs3rdDp1e6.gwascatalog.tsv_2"
gwas_EUdata = pd.read_csv(path, sep='\t')
display(gwas_EUdata)

,chromosome,base_pair_location,effect_allele_frequency,beta,standard_error,p_value,odds_ratio,ci_lower,ci_upper,effect_allele,other_allele
0,5,29439275,0.3566,0.0069,0.0076,0.36030,1.006924,0.992036,1.022035,T,C
1,5,85928892,0.0635,-0.0148,0.0150,0.32290,0.985309,0.956763,1.014707,T,C
2,10,128341232,0.4610,0.0069,0.0071,0.33070,1.006924,0.993009,1.021034,T,C
3,3,62707519,0.0536,0.0169,0.0164,0.30460,1.017044,0.984872,1.050267,T,C
4,2,80464120,0.9785,-0.0043,0.0273,0.87490,0.995709,0.943831,1.050439,T,G
...,...,...,...,...,...,...,...,...,...,...,...
7482027,3,80436770,0.9578,-0.0460,0.0190,0.01529,0.955042,0.920130,0.991278,A,G
7482028,18,44156714,0.1847,0.0044,0.0093,0.63330,1.004410,0.986267,1.022886,C,G
7482029,5,95076854,0.9176,-0.0179,0.0139,0.19660,0.982259,0.955860,1.009388,A,G
7482030,11,99622387,0.8017,0.0127,0.0088,0.15010,1.012781,0.995462,1.030401,T,C
7482031,4,104138439,0.0265,0.0368,0.0256,0.15070,1.037486,0.986713,1.090870,A,G

In [6]:
rename_dict = {
    'chromosome': 'CHR',
    'base_pair_location': 'BP',
    'effect_allele': 'A1',      # A1 is the target/risk allele
    'other_allele': 'A2',       # A2 is the baseline allele
    'beta': 'BETA',
    'p_value': 'P',
    'effect_allele_frequency': 'EAF',
    'standard_error': 'SE',
    'odds_ratio': 'OR'
}

In [7]:
eurename = gwas_EUdata.rename(columns=rename_dict)

In [8]:
eurename

,CHR,BP,EAF,BETA,SE,P,OR,ci_lower,ci_upper,A1,A2
0,5,29439275,0.3566,0.0069,0.0076,0.36030,1.006924,0.992036,1.022035,T,C
1,5,85928892,0.0635,-0.0148,0.0150,0.32290,0.985309,0.956763,1.014707,T,C
2,10,128341232,0.4610,0.0069,0.0071,0.33070,1.006924,0.993009,1.021034,T,C
3,3,62707519,0.0536,0.0169,0.0164,0.30460,1.017044,0.984872,1.050267,T,C
4,2,80464120,0.9785,-0.0043,0.0273,0.87490,0.995709,0.943831,1.050439,T,G
...,...,...,...,...,...,...,...,...,...,...,...
7482027,3,80436770,0.9578,-0.0460,0.0190,0.01529,0.955042,0.920130,0.991278,A,G
7482028,18,44156714,0.1847,0.0044,0.0093,0.63330,1.004410,0.986267,1.022886,C,G
7482029,5,95076854,0.9176,-0.0179,0.0139,0.19660,0.982259,0.955860,1.009388,A,G
7482030,11,99622387,0.8017,0.0127,0.0088,0.15010,1.012781,0.995462,1.030401,T,C
7482031,4,104138439,0.0265,0.0368,0.0256,0.15070,1.037486,0.986713,1.090870,A,G

In [9]:
columns_to_keep = ['CHR', 'BP', 'A1', 'A2', 'BETA', 'P', 'EAF', 'SE', 'OR'] 
eu = eurename[columns_to_keep]
eu

         CHR         BP A1 A2    BETA        P     EAF      SE        OR
0          5   29439275  T  C  0.0069  0.36030  0.3566  0.0076  1.006924
1          5   85928892  T  C -0.0148  0.32290  0.0635  0.0150  0.985309
2         10  128341232  T  C  0.0069  0.33070  0.4610  0.0071  1.006924
3          3   62707519  T  C  0.0169  0.30460  0.0536  0.0164  1.017044
4          2   80464120  T  G -0.0043  0.87490  0.9785  0.0273  0.995709
...      ...        ... .. ..     ...      ...     ...     ...       ...
7482027    3   80436770  A  G -0.0460  0.01529  0.9578  0.0190  0.955042
7482028   18   44156714  C  G  0.0044  0.63330  0.1847  0.0093  1.004410
7482029    5   95076854  A  G -0.0179  0.19660  0.9176  0.0139  0.982259
7482030   11   99622387  T  C  0.0127  0.15010  0.8017  0.0088  1.012781
7482031    4  104138439  A  G  0.0368  0.15070  0.0265  0.0256  1.037486

[7482032 rows x 9 columns]

In [10]:
missing = eu.isna().sum()
print(missing)

CHR     0
BP      0
A1      0
A2      0
BETA    0
P       0
EAF     0
SE      0
OR      0
dtype: int64

In [11]:
eu['MAF'] = np.where(
    eu['EAF'] > 0.5,     # The IF condition because Minor Alleles need to be less than 0.5, if effect allele is less than 0.5, calculation does not apply and MAF = EAF
    1 - eu['EAF'],       # What to do if TRUE
    eu['EAF']            # What to do if FALSE
)

C:\Users\micha\AppData\Local\Temp\ipykernel_13112\852985553.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eu['MAF'] = np.where(

In [12]:
eu

,CHR,BP,A1,A2,BETA,P,EAF,SE,OR,MAF
0,5,29439275,T,C,0.0069,0.36030,0.3566,0.0076,1.006924,0.3566
1,5,85928892,T,C,-0.0148,0.32290,0.0635,0.0150,0.985309,0.0635
2,10,128341232,T,C,0.0069,0.33070,0.4610,0.0071,1.006924,0.4610
3,3,62707519,T,C,0.0169,0.30460,0.0536,0.0164,1.017044,0.0536
4,2,80464120,T,G,-0.0043,0.87490,0.9785,0.0273,0.995709,0.0215
...,...,...,...,...,...,...,...,...,...,...
7482027,3,80436770,A,G,-0.0460,0.01529,0.9578,0.0190,0.955042,0.0422
7482028,18,44156714,C,G,0.0044,0.63330,0.1847,0.0093,1.004410,0.1847
7482029,5,95076854,A,G,-0.0179,0.19660,0.9176,0.0139,0.982259,0.0824
7482030,11,99622387,T,C,0.0127,0.15010,0.8017,0.0088,1.012781,0.1983
7482031,4,104138439,A,G,0.0368,0.15070,0.0265,0.0256,1.037486,0.0265

In [13]:
# Find the lowest and highest EAF in your data, for sanity check if calculations were wrong
min_eaf = eu['EAF'].min() 
max_eaf = eu['EAF'].max()

print(f"The lowest EAF is: {min_eaf}")
print(f"The highest EAF is: {max_eaf}")

The lowest EAF is: 0.0104
The highest EAF is: 0.9895

In [14]:
eu = eu[eu['MAF'] >= 0.01] # Filtering SNPs with MAF less than 1%, theory is this may be only noise

In [15]:
# Check for duplicate SNPs
print(eu.duplicated(subset=['CHR', 'BP']).sum())

0

In [16]:
min_p = eu['P'].min() 
max_p = eu['P'].max()

print(f"The lowest p is: {min_p}")
print(f"The highest p is: {max_p}")

The lowest p is: 7.181e-20
The highest p is: 1.0

In [19]:
eu = eu[(eu['P'] > 0) & (eu['P'] <= 1)]

In [20]:
eu

,CHR,BP,A1,A2,BETA,P,EAF,SE,OR,MAF
0,5,29439275,T,C,0.0069,0.36030,0.3566,0.0076,1.006924,0.3566
1,5,85928892,T,C,-0.0148,0.32290,0.0635,0.0150,0.985309,0.0635
2,10,128341232,T,C,0.0069,0.33070,0.4610,0.0071,1.006924,0.4610
3,3,62707519,T,C,0.0169,0.30460,0.0536,0.0164,1.017044,0.0536
4,2,80464120,T,G,-0.0043,0.87490,0.9785,0.0273,0.995709,0.0215
...,...,...,...,...,...,...,...,...,...,...
7482027,3,80436770,A,G,-0.0460,0.01529,0.9578,0.0190,0.955042,0.0422
7482028,18,44156714,C,G,0.0044,0.63330,0.1847,0.0093,1.004410,0.1847
7482029,5,95076854,A,G,-0.0179,0.19660,0.9176,0.0139,0.982259,0.0824
7482030,11,99622387,T,C,0.0127,0.15010,0.8017,0.0088,1.012781,0.1983
7482031,4,104138439,A,G,0.0368,0.15070,0.0265,0.0256,1.037486,0.0265

In [21]:
eu.to_csv('EU_Data_Gigastroke_Cleaned.txt', sep='\t', index=False)