In [1]:
import pandas as pd
import numpy as np

In [2]:
path = r"C:\Users\micha\OneDrive\Documents\PRSGWAS_tsv\GCST90104555_buildGRCh37LA.tsv\Meta_IS_BothMandF_GIGA_HA_allfiles_metaAnalyseSEbased_wogc_2021June11_NeNs3rdDp1e6.gwascatalog.tsv_2"
gwas_LAdata = pd.read_csv(path, sep='\t')
display(gwas_LAdata)

,chromosome,base_pair_location,effect_allele_frequency,beta,standard_error,p_value,odds_ratio,ci_lower,ci_upper,effect_allele,other_allele
0,5,29439275,0.3769,0.0600,0.0796,0.45100,1.061837,0.908449,1.241122,T,C
1,5,85928892,0.1025,-0.1119,0.1391,0.42120,0.894134,0.680766,1.174375,T,C
2,10,128341232,0.5093,-0.0329,0.0785,0.67520,0.967635,0.829643,1.128580,T,C
3,3,62707519,0.0727,0.2020,0.1520,0.18400,1.223848,0.908537,1.648589,T,C
4,2,80464120,0.8872,0.0634,0.1367,0.64250,1.065453,0.815029,1.392822,T,G
...,...,...,...,...,...,...,...,...,...,...,...
7277668,7,118234612,0.4754,0.0474,0.0766,0.53600,1.048541,0.902365,1.218397,A,G
7277669,4,142125833,0.0448,0.4711,0.2322,0.04251,1.601755,1.016116,2.524927,T,C
7277670,18,44156714,0.2451,0.0997,0.0943,0.29020,1.104839,0.918395,1.329135,C,G
7277671,11,99622387,0.7205,-0.0982,0.0892,0.27120,0.906468,0.761068,1.079645,T,C
7277672,3,181867629,0.0507,0.4342,0.2530,0.08618,1.543728,0.940184,2.534712,T,C

In [3]:
rename_dict = {
    'chromosome': 'CHR',
    'base_pair_location': 'BP',
    'effect_allele': 'A1',      # A1 is the target/risk allele
    'other_allele': 'A2',       # A2 is the baseline allele
    'beta': 'BETA',
    'p_value': 'P',
    'effect_allele_frequency': 'EAF',
    'standard_error': 'SE',
    'odds_ratio': 'OR'
}

In [4]:
larename = gwas_LAdata.rename(columns=rename_dict)

In [5]:
larename

,CHR,BP,EAF,BETA,SE,P,OR,ci_lower,ci_upper,A1,A2
0,5,29439275,0.3769,0.0600,0.0796,0.45100,1.061837,0.908449,1.241122,T,C
1,5,85928892,0.1025,-0.1119,0.1391,0.42120,0.894134,0.680766,1.174375,T,C
2,10,128341232,0.5093,-0.0329,0.0785,0.67520,0.967635,0.829643,1.128580,T,C
3,3,62707519,0.0727,0.2020,0.1520,0.18400,1.223848,0.908537,1.648589,T,C
4,2,80464120,0.8872,0.0634,0.1367,0.64250,1.065453,0.815029,1.392822,T,G
...,...,...,...,...,...,...,...,...,...,...,...
7277668,7,118234612,0.4754,0.0474,0.0766,0.53600,1.048541,0.902365,1.218397,A,G
7277669,4,142125833,0.0448,0.4711,0.2322,0.04251,1.601755,1.016116,2.524927,T,C
7277670,18,44156714,0.2451,0.0997,0.0943,0.29020,1.104839,0.918395,1.329135,C,G
7277671,11,99622387,0.7205,-0.0982,0.0892,0.27120,0.906468,0.761068,1.079645,T,C
7277672,3,181867629,0.0507,0.4342,0.2530,0.08618,1.543728,0.940184,2.534712,T,C

In [6]:
columns_to_keep = ['CHR', 'BP', 'A1', 'A2', 'BETA', 'P', 'EAF', 'SE', 'OR'] 
la = larename[columns_to_keep]
la

         CHR         BP A1 A2    BETA        P     EAF      SE        OR
0          5   29439275  T  C  0.0600  0.45100  0.3769  0.0796  1.061837
1          5   85928892  T  C -0.1119  0.42120  0.1025  0.1391  0.894134
2         10  128341232  T  C -0.0329  0.67520  0.5093  0.0785  0.967635
3          3   62707519  T  C  0.2020  0.18400  0.0727  0.1520  1.223848
4          2   80464120  T  G  0.0634  0.64250  0.8872  0.1367  1.065453
...      ...        ... .. ..     ...      ...     ...     ...       ...
7277668    7  118234612  A  G  0.0474  0.53600  0.4754  0.0766  1.048541
7277669    4  142125833  T  C  0.4711  0.04251  0.0448  0.2322  1.601755
7277670   18   44156714  C  G  0.0997  0.29020  0.2451  0.0943  1.104839
7277671   11   99622387  T  C -0.0982  0.27120  0.7205  0.0892  0.906468
7277672    3  181867629  T  C  0.4342  0.08618  0.0507  0.2530  1.543728

[7277673 rows x 9 columns]

In [7]:
missing = la.isna().sum()
print(missing)

CHR     0
BP      0
A1      0
A2      0
BETA    0
P       0
EAF     0
SE      0
OR      0
dtype: int64

In [8]:
la['MAF'] = np.where(
    la['EAF'] > 0.5,     # The IF condition because Minor Alleles need to be less than 0.5, if effect allele is less than 0.5, calculation does not apply and MAF = EAF
    1 - la['EAF'],       # What to do if TRUE
    la['EAF']            # What to do if FALSE
)

C:\Users\micha\AppData\Local\Temp\ipykernel_19800\2831706662.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  la['MAF'] = np.where(

In [9]:
la

,CHR,BP,A1,A2,BETA,P,EAF,SE,OR,MAF
0,5,29439275,T,C,0.0600,0.45100,0.3769,0.0796,1.061837,0.3769
1,5,85928892,T,C,-0.1119,0.42120,0.1025,0.1391,0.894134,0.1025
2,10,128341232,T,C,-0.0329,0.67520,0.5093,0.0785,0.967635,0.4907
3,3,62707519,T,C,0.2020,0.18400,0.0727,0.1520,1.223848,0.0727
4,2,80464120,T,G,0.0634,0.64250,0.8872,0.1367,1.065453,0.1128
...,...,...,...,...,...,...,...,...,...,...
7277668,7,118234612,A,G,0.0474,0.53600,0.4754,0.0766,1.048541,0.4754
7277669,4,142125833,T,C,0.4711,0.04251,0.0448,0.2322,1.601755,0.0448
7277670,18,44156714,C,G,0.0997,0.29020,0.2451,0.0943,1.104839,0.2451
7277671,11,99622387,T,C,-0.0982,0.27120,0.7205,0.0892,0.906468,0.2795
7277672,3,181867629,T,C,0.4342,0.08618,0.0507,0.2530,1.543728,0.0507

In [10]:
# Find the lowest and highest EAF in your data, for sanity check if calculations were wrong
min_eaf = la['EAF'].min() 
max_eaf = la['EAF'].max()

print(f"The lowest EAF is: {min_eaf}")
print(f"The highest EAF is: {max_eaf}")

The lowest EAF is: 0.01
The highest EAF is: 0.99

In [11]:
la = la[la['MAF'] >= 0.01] # Filtering SNPs with MAF less than 1%, theory is this may be only noise

In [12]:
# Check for duplicate SNPs
print(la.duplicated(subset=['CHR', 'BP']).sum())

0

In [13]:
min_p = la['P'].min() 
max_p = la['P'].max()

print(f"The lowest p is: {min_p}")
print(f"The highest p is: {max_p}")

The lowest p is: 4.683e-08
The highest p is: 1.0

In [14]:
la = la[(la['P'] > 0) & (la['P'] <= 1)]

In [15]:
la

,CHR,BP,A1,A2,BETA,P,EAF,SE,OR,MAF
0,5,29439275,T,C,0.0600,0.45100,0.3769,0.0796,1.061837,0.3769
1,5,85928892,T,C,-0.1119,0.42120,0.1025,0.1391,0.894134,0.1025
2,10,128341232,T,C,-0.0329,0.67520,0.5093,0.0785,0.967635,0.4907
3,3,62707519,T,C,0.2020,0.18400,0.0727,0.1520,1.223848,0.0727
4,2,80464120,T,G,0.0634,0.64250,0.8872,0.1367,1.065453,0.1128
...,...,...,...,...,...,...,...,...,...,...
7277668,7,118234612,A,G,0.0474,0.53600,0.4754,0.0766,1.048541,0.4754
7277669,4,142125833,T,C,0.4711,0.04251,0.0448,0.2322,1.601755,0.0448
7277670,18,44156714,C,G,0.0997,0.29020,0.2451,0.0943,1.104839,0.2451
7277671,11,99622387,T,C,-0.0982,0.27120,0.7205,0.0892,0.906468,0.2795
7277672,3,181867629,T,C,0.4342,0.08618,0.0507,0.2530,1.543728,0.0507

In [16]:
la.to_csv('LA_Data_Gigastroke_Cleaned.txt', sep='\t', index=False)