In [2]:
import pandas as pd
import numpy as np

In [3]:
path = r"C:\Users\micha\OneDrive\Documents\PRSGWAS_tsv\GCST90104560_buildGRCh37SA.tsv\Meta_IS_BothMandF_GIGA_SAS_allfiles_metaAnalyseSEbased_wogc_2021June11_NeNs3rdDp1e6.gwascatalog.tsv_2"
gwas_SAdata = pd.read_csv(path, sep='\t')
display(gwas_SAdata)

,chromosome,base_pair_location,effect_allele_frequency,beta,standard_error,p_value,odds_ratio,ci_lower,ci_upper,effect_allele,other_allele
0,5,85928892,0.0482,0.0719,0.1079,0.50510,1.074548,0.869720,1.327615,T,C
1,2,80464120,0.9599,-0.0941,0.1023,0.35770,0.910192,0.744824,1.112276,T,G
2,3,62707519,0.0958,-0.0225,0.0689,0.74430,0.977751,0.854239,1.119121,T,C
3,9,109166464,0.9314,-0.0897,0.0884,0.31050,0.914205,0.768770,1.087155,A,T
4,7,67244641,0.5652,-0.0601,0.0409,0.14140,0.941670,0.869129,1.020267,A,G
...,...,...,...,...,...,...,...,...,...,...,...
3306948,11,115938451,0.0483,-0.0484,0.1064,0.64910,0.952753,0.773412,1.173680,T,C
3306949,3,36450850,0.0159,-0.0065,0.1690,0.96940,0.993521,0.713381,1.383671,A,G
3306950,6,128516191,0.0253,-0.0610,0.1309,0.64120,0.940823,0.727920,1.215997,A,G
3306951,7,118234612,0.5102,0.0974,0.0405,0.01623,1.102301,1.018183,1.193369,A,G
3306952,18,44156714,0.2066,0.0755,0.0548,0.16830,1.078423,0.968596,1.200704,C,G

In [4]:
rename_dict = {
    'chromosome': 'CHR',
    'base_pair_location': 'BP',
    'effect_allele': 'A1',      # A1 is the target/risk allele
    'other_allele': 'A2',       # A2 is the baseline allele
    'beta': 'BETA',
    'p_value': 'P',
    'effect_allele_frequency': 'EAF',
    'standard_error': 'SE',
    'odds_ratio': 'OR'
}

In [5]:
sarename = gwas_SAdata.rename(columns=rename_dict)

In [6]:
sarename

,CHR,BP,EAF,BETA,SE,P,OR,ci_lower,ci_upper,A1,A2
0,5,85928892,0.0482,0.0719,0.1079,0.50510,1.074548,0.869720,1.327615,T,C
1,2,80464120,0.9599,-0.0941,0.1023,0.35770,0.910192,0.744824,1.112276,T,G
2,3,62707519,0.0958,-0.0225,0.0689,0.74430,0.977751,0.854239,1.119121,T,C
3,9,109166464,0.9314,-0.0897,0.0884,0.31050,0.914205,0.768770,1.087155,A,T
4,7,67244641,0.5652,-0.0601,0.0409,0.14140,0.941670,0.869129,1.020267,A,G
...,...,...,...,...,...,...,...,...,...,...,...
3306948,11,115938451,0.0483,-0.0484,0.1064,0.64910,0.952753,0.773412,1.173680,T,C
3306949,3,36450850,0.0159,-0.0065,0.1690,0.96940,0.993521,0.713381,1.383671,A,G
3306950,6,128516191,0.0253,-0.0610,0.1309,0.64120,0.940823,0.727920,1.215997,A,G
3306951,7,118234612,0.5102,0.0974,0.0405,0.01623,1.102301,1.018183,1.193369,A,G
3306952,18,44156714,0.2066,0.0755,0.0548,0.16830,1.078423,0.968596,1.200704,C,G

In [7]:
columns_to_keep = ['CHR', 'BP', 'A1', 'A2', 'BETA', 'P', 'EAF', 'SE', 'OR'] 
sa = sarename[columns_to_keep]
sa

         CHR         BP A1 A2    BETA        P     EAF      SE        OR
0          5   85928892  T  C  0.0719  0.50510  0.0482  0.1079  1.074548
1          2   80464120  T  G -0.0941  0.35770  0.9599  0.1023  0.910192
2          3   62707519  T  C -0.0225  0.74430  0.0958  0.0689  0.977751
3          9  109166464  A  T -0.0897  0.31050  0.9314  0.0884  0.914205
4          7   67244641  A  G -0.0601  0.14140  0.5652  0.0409  0.941670
...      ...        ... .. ..     ...      ...     ...     ...       ...
3306948   11  115938451  T  C -0.0484  0.64910  0.0483  0.1064  0.952753
3306949    3   36450850  A  G -0.0065  0.96940  0.0159  0.1690  0.993521
3306950    6  128516191  A  G -0.0610  0.64120  0.0253  0.1309  0.940823
3306951    7  118234612  A  G  0.0974  0.01623  0.5102  0.0405  1.102301
3306952   18   44156714  C  G  0.0755  0.16830  0.2066  0.0548  1.078423

[3306953 rows x 9 columns]

In [8]:
missing = sa.isna().sum()
print(missing)

CHR     0
BP      0
A1      0
A2      0
BETA    0
P       0
EAF     0
SE      0
OR      0
dtype: int64

In [9]:
sa['MAF'] = np.where(
    sa['EAF'] > 0.5,     # The IF condition because Minor Alleles need to be less than 0.5, if effect allele is less than 0.5, calculation does not apply and MAF = EAF
    1 - sa['EAF'],       # What to do if TRUE
    sa['EAF']            # What to do if FALSE
)

C:\Users\micha\AppData\Local\Temp\ipykernel_20280\3181962588.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sa['MAF'] = np.where(

In [10]:
sa

,CHR,BP,A1,A2,BETA,P,EAF,SE,OR,MAF
0,5,85928892,T,C,0.0719,0.50510,0.0482,0.1079,1.074548,0.0482
1,2,80464120,T,G,-0.0941,0.35770,0.9599,0.1023,0.910192,0.0401
2,3,62707519,T,C,-0.0225,0.74430,0.0958,0.0689,0.977751,0.0958
3,9,109166464,A,T,-0.0897,0.31050,0.9314,0.0884,0.914205,0.0686
4,7,67244641,A,G,-0.0601,0.14140,0.5652,0.0409,0.941670,0.4348
...,...,...,...,...,...,...,...,...,...,...
3306948,11,115938451,T,C,-0.0484,0.64910,0.0483,0.1064,0.952753,0.0483
3306949,3,36450850,A,G,-0.0065,0.96940,0.0159,0.1690,0.993521,0.0159
3306950,6,128516191,A,G,-0.0610,0.64120,0.0253,0.1309,0.940823,0.0253
3306951,7,118234612,A,G,0.0974,0.01623,0.5102,0.0405,1.102301,0.4898
3306952,18,44156714,C,G,0.0755,0.16830,0.2066,0.0548,1.078423,0.2066

In [11]:
# Find the lowest and highest EAF in your data, for sanity check if calculations were wrong
min_eaf = sa['EAF'].min() 
max_eaf = sa['EAF'].max()

print(f"The lowest EAF is: {min_eaf}")
print(f"The highest EAF is: {max_eaf}")

The lowest EAF is: 0.0101
The highest EAF is: 0.9899

In [12]:
sa = sa[sa['MAF'] >= 0.01] # Filtering SNPs with MAF less than 1%, theory is this may be only noise

In [13]:
# Check for duplicate SNPs
print(sa.duplicated(subset=['CHR', 'BP']).sum())

0

In [14]:
min_p = sa['P'].min() 
max_p = sa['P'].max()

print(f"The lowest p is: {min_p}")
print(f"The highest p is: {max_p}")

The lowest p is: 3.524e-08
The highest p is: 1.0

In [15]:
sa = sa[(sa['P'] > 0) & (sa['P'] <= 1)]

In [16]:
sa

,CHR,BP,A1,A2,BETA,P,EAF,SE,OR,MAF
0,5,85928892,T,C,0.0719,0.50510,0.0482,0.1079,1.074548,0.0482
1,2,80464120,T,G,-0.0941,0.35770,0.9599,0.1023,0.910192,0.0401
2,3,62707519,T,C,-0.0225,0.74430,0.0958,0.0689,0.977751,0.0958
3,9,109166464,A,T,-0.0897,0.31050,0.9314,0.0884,0.914205,0.0686
4,7,67244641,A,G,-0.0601,0.14140,0.5652,0.0409,0.941670,0.4348
...,...,...,...,...,...,...,...,...,...,...
3306948,11,115938451,T,C,-0.0484,0.64910,0.0483,0.1064,0.952753,0.0483
3306949,3,36450850,A,G,-0.0065,0.96940,0.0159,0.1690,0.993521,0.0159
3306950,6,128516191,A,G,-0.0610,0.64120,0.0253,0.1309,0.940823,0.0253
3306951,7,118234612,A,G,0.0974,0.01623,0.5102,0.0405,1.102301,0.4898
3306952,18,44156714,C,G,0.0755,0.16830,0.2066,0.0548,1.078423,0.2066

In [17]:
sa.to_csv('SA_Data_Gigastroke_Cleaned.txt', sep='\t', index=False)